### ISSUE TITLE
Piping is broken

### ISSUE THREAD

**Issue by coderstephen** [bucaran/shark#2]
Switching Shark to be a function breaks reading numbers from STDIN, and causes spec tests to fail. See https://github.com/oh-my-fish/plugin-shark/issues/1.

**Comment by bucaran** [comment]
https://github.com/oh-my-fish/plugin-shark/issues/1

**Comment by bucaran** [comment]
Please see the BUGS section in the bundled [man page](https://github.com/bucaran/shark/blob/master/man/man1/shark.md#bugs).
