### ISSUE TITLE
Official OMF package status

### ISSUE THREAD

**Issue by coderstephen** [bucaran/shark#3]
Hey @bucaran, would it be better for this repository to be the source for the official `shark` package in the Oh My Fish package database? I know I ported one [here](https://github.com/oh-my-fish/plugin-shark), but it looks like your latest version is at least minimally compatible with the framework now. I don't really want to maintain a fork anyway.

My only comment is that it would be better for performance for `shark.fish` to be put into a `functions` directory to be autoloaded, but might that make it less friendly to other uses?

Thanks for the excellent code, by the way!

**Comment by bucaran** [comment]
That makes sense. Your port was of the first version in which everything was split into 3 functions (I didn't know much fish at the time and my design was poor), but now it's just one [file(https://github.com/bucaran/shark/blob/master/shark.fish). There won't be any additional files, so there is no need for a `functions` directory. We could add a `completions` directory with a `shark.fish` file, and I will be adding tests later on.

**Comment by coderstephen** [comment]
> There won't be any additional files either, why the `functions` directory?

No other reason than the fact that OMF adds `$pkg_name/functions` to the function autoload path, and evaluates every fish file in `$pkg_name/` at start up, which slows down start-up time.

**Comment by coderstephen** [comment]
> We should add a completions directory with a shark.fish file, and I will be adding tests later on.

Also, yes! Good idea.

**Comment by bucaran** [comment]
Alright, I will start porting the tests and then we can figure this out.

**Comment by bucaran** [comment]
@coderstephen I have released [Fisherman](https://github.com/fisherman/fisherman), but made Spark work as a standalone utility too so that you can use it in OMF too. 

In the end I didn't add a `functions` directory, because Fisherman does not need it and because if I was going to make this package really a stand alone fish addon it would not make sense to support Oh My Fish! specifically.

**Comment by coderstephen** [comment]
Any chance you still have those original speed improvements to the old version still laying around so I can adapt them into the fork for right now? The ones that replaced `shark.split()`?

**Comment by bucaran** [comment]
I don't think so, but the current version is even faster now that all the core is written in AWK, we also have realtime streaming for data, and a large test coverage for every little detail I could find. 

Oh, and the documentation via man pages.

This is not a toy anymore.

**Comment by coderstephen** [comment]
That's great, but the latest version is again no longer compatible with OMF's generic plugin structure, so it no longer works out of the box. Perhaps consider adding an `init.fish`, or something along those lines, that autoloads `src/shark.fish`. Otherwise I can continue maintaining an OMF-installable fork if you prefer that approach.

I can sync the fork to the latest version when I get a chance.

**Comment by bucaran** [comment]
@coderstephen There is nothing really _generic_ about OMF plugin structure which is the same as Wahoo, which I wrote. 

For Fisherman, all you need to do is clone the repo, run make to generate the `shark.fish` file and add it to a path in the functions directory.

Screencast: http://showterm.io/c711f508c2d2adf6ad649

Also, consider joining Fisherman, tons of more powerful features, robust UNIX ties, extensive documentation and backward compatible with Oh My Fish.

**Comment by coderstephen** [comment]
Thanks! :+1: I'll try that and see what I can do.

> Also, consider joining Fisherman, tons of more powerful features, robust UNIX ties, extensive documentation and backward compatible with Oh My Fish.

I'll see how it plays out and is adopted first. A great open-source project is 50% great code, and 50% great community.

**Comment by bucaran** [comment]
:+1:

**Comment by bucaran** [comment]
:+1:
